//  words
export const UPDATE_WORDS = 'UPDATE_WORDS';
export const ADD_WORD = 'ADD_WORD';

// search
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const REFRESH_SEARCH_RESULTS = 'REFRESH_SEARCH_RESULTS';
